Repository javascript-tutorial/ro.javascript.info, pull requests merged in 2022-11, with the labels that each got.

#132 minor fix
  1-js/01-getting-started/2-manuals-specifications/article.md
Labels: review needed

#133 Updated entire 01-getting-started
  1-js/01-getting-started/1-intro/article.md
  1-js/01-getting-started/3-code-editors/article.md
Labels: review needed

#134 Updated sections to match
  1-js/02-first-steps/14-switch/article.md
  1-js/03-code-quality/03-comments/article.md
Labels: review needed

#135 Fixed conflicts
  1-js/01-getting-started/index.md
  1-js/04-object-basics/01-object/5-sum-object/task.md
  1-js/04-object-basics/01-object/8-multiply-numeric/task.md
  1-js/04-object-basics/03-garbage-collection/article.md
  1-js/04-object-basics/04-object-methods/4-object-property-this/solution.md
  1-js/04-object-basics/04-object-methods/article.md
  1-js/index.md
Labels: review needed

#136 fixed conflicts and minor updates
  1-js/03-code-quality/03-comments/article.md
  1-js/04-object-basics/08-symbol/article.md
  1-js/04-object-basics/index.md
Labels: review needed

#137 Updates and fixed conflicts
  1-js/04-object-basics/04-object-methods/7-calculator/task.md
  1-js/04-object-basics/04-object-methods/8-chain-calls/solution.md
  1-js/04-object-basics/04-object-methods/article.md
  1-js/04-object-basics/08-symbol/article.md
  1-js/06-advanced-functions/03-closure/article.md
  1-js/11-async/02-promise-basics/article.md
  1-js/99-js-misc/01-proxy/article.md
  1-js/99-js-misc/04-reference-type/2-check-syntax/solution.md
  1-js/99-js-misc/04-reference-type/2-check-syntax/task.md
  1-js/99-js-misc/04-reference-type/3-why-this/solution.md
  1-js/99-js-misc/04-reference-type/3-why-this/task.md
  1-js/99-js-misc/04-reference-type/article.md
Labels: review needed

#139 Sync 29216730
  2-ui/3-event-details/3-mousemove-mouseover-mouseout-mouseenter-mouseleave/article.md
  2-ui/99-ui-misc/03-event-loop/article.md
  README.md
Labels: review needed

#140 Updated README.md and entire 1-js/02-first-steps/10-ifelse/ folder
  1-js/02-first-steps/10-ifelse/1-if-zero-string/solution.md
  1-js/02-first-steps/10-ifelse/1-if-zero-string/task.md
  1-js/02-first-steps/10-ifelse/2-check-standard/ifelse_task2/index.html
  1-js/02-first-steps/10-ifelse/2-check-standard/task.md
  1-js/02-first-steps/10-ifelse/3-sign/solution.md
  1-js/02-first-steps/10-ifelse/3-sign/task.md
  1-js/02-first-steps/10-ifelse/5-rewrite-if-question/solution.md
  1-js/02-first-steps/10-ifelse/5-rewrite-if-question/task.md
  1-js/02-first-steps/10-ifelse/6-rewrite-if-else-question/solution.md
  1-js/02-first-steps/10-ifelse/6-rewrite-if-else-question/task.md
  1-js/02-first-steps/10-ifelse/article.md
  README.md
Labels: review needed

#143 update
  README.md
Labels: review needed

#48 Hello, world!
  1-js/02-first-steps/01-hello-world/1-hello-alert/solution.view/index.html
  1-js/02-first-steps/01-hello-world/1-hello-alert/task.md
  1-js/02-first-steps/01-hello-world/2-hello-alert-ext/alert.js
  1-js/02-first-steps/01-hello-world/2-hello-alert-ext/solution.md
  1-js/02-first-steps/01-hello-world/2-hello-alert-ext/task.md
  1-js/02-first-steps/01-hello-world/article.md
Labels: changes requested

#49 translated code structure
  1-js/02-first-steps/02-structure/article.md
Labels: changes requested

#141 Type Conversions
  1-js/02-first-steps/07-type-conversions/article.md
  1-js/02-first-steps/08-operators/1-increment-order/solution.md
  1-js/02-first-steps/08-operators/1-increment-order/task.md
  1-js/02-first-steps/08-operators/2-assignment-result/solution.md
  1-js/02-first-steps/08-operators/2-assignment-result/task.md
  1-js/02-first-steps/08-operators/3-primitive-conversions-questions/solution.md
  1-js/02-first-steps/08-operators/3-primitive-conversions-questions/task.md
Labels: needs +1

#144 Structure
  1-js/02-first-steps/02-structure/article.md
  1-js/02-first-steps/08-operators/2-assignment-result/task.md
Labels: review needed

#145 Hello world
  1-js/02-first-steps/01-hello-world/1-hello-alert/index.html
  1-js/02-first-steps/01-hello-world/2-hello-alert-ext/alert.js
  1-js/02-first-steps/01-hello-world/article.md
Labels: review needed

#146 Tmp 40
  1-js/09-classes/01-class/1-rewrite-to-class/task.md
  1-js/09-classes/01-class/article.md
Labels: needs +1

#148 Introduction: callbacks
  1-js/11-async/01-callbacks/article.md
Labels: review needed

#149 callbacks final polish
  1-js/11-async/01-callbacks/article.md
Labels: review needed

#150 Promise
  1-js/11-async/02-promise-basics/01-re-resolve/solution.md
  1-js/11-async/02-promise-basics/01-re-resolve/task.md
  1-js/11-async/02-promise-basics/02-delay-promise/solution.md
  1-js/11-async/02-promise-basics/02-delay-promise/task.md
  1-js/11-async/02-promise-basics/03-animate-circle-promise/task.md
  1-js/11-async/02-promise-basics/article.md
  1-js/11-async/02-promise-basics/head.html
Labels: review needed
